# config.toml
debug = false

interval_secs = 10
batch_size=128
total_batches=20000
input_number=6
output_number=3
hidden_layers=16
reply_capacity=4096
model_name="model-128.json"
log_interval=64
mode="Infer"
